spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/bankdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    drop-first: false
    contexts: prod

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    secret: ${APP_JWT_SECRET:YourSuperSecretKeyForJwtSigningMustBeLongEnough12345}
    expiration-ms: ${APP_JWT_EXPIRATION_MS:86400000}

  encryption:
    secret: ${APP_ENCRYPTION_SECRET:1234567890123456}

logging:
  level:
    liquibase: INFO
    org.springframework.security: INFO
    root: WARN 